name: Deploy package to GitHub feed

on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'A name to be used to publish artifact'
        default: 'Package'
        required: false
        type: string

jobs:

  publish:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: '1'
      DOTNET_CLI_TELEMETRY_OPTOUT: '1'

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: '${{ inputs.artifact-name }}'
        path: artifact

    - name: Publish Package
      run: |
        dotnet nuget add source "https://nuget.pkg.github.com/unitycontainer/index.json" -n github -u unitycontainer -p ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text
        dotnet nuget push 'artifact\*' --skip-duplicate --source github
